version: "3.5"

services:
  app:
    image: viktor:1
    restart: unless-stopped
    container_name: viktor
    volumes:
      - viktor-data:/usr/src/app
    ports:
      - "8888:3000"
    networks:
      - viktor-network

volumes:
  viktor-data:

networks:
  viktor-network:
    driver: bridge
