// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma-pcvisit-database/schema.prisma",
  migrations: {
    path: "prisma-pcvisit-database/migrations",
  },
  datasource: {
    url: `sqlserver://${env("INTREXX_DATABASE_HOST")};database=${env("PCVISIT_DATABASE_NAME")};user=${env("INTREXX_DATABASE_USER")};password=${env("INTREXX_DATABASE_PASSWORD")};encrypt=true;trustServerCertificate=true`,
  },
});
