/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/protected'
import { Route as Not_allowedRouteImport } from './routes/not_allowed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EinkaufIndexRouteImport } from './routes/Einkauf/index'
import { Route as EinkaufMaIdIndexRouteImport } from './routes/Einkauf/$maId/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/protected',
  path: '/protected',
  getParentRoute: () => rootRouteImport,
} as any)
const Not_allowedRoute = Not_allowedRouteImport.update({
  id: '/not_allowed',
  path: '/not_allowed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EinkaufIndexRoute = EinkaufIndexRouteImport.update({
  id: '/Einkauf/',
  path: '/Einkauf/',
  getParentRoute: () => rootRouteImport,
} as any)
const EinkaufMaIdIndexRoute = EinkaufMaIdIndexRouteImport.update({
  id: '/Einkauf/$maId/',
  path: '/Einkauf/$maId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/not_allowed': typeof Not_allowedRoute
  '/protected': typeof ProtectedRoute
  '/Einkauf/': typeof EinkaufIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/Einkauf/$maId/': typeof EinkaufMaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/not_allowed': typeof Not_allowedRoute
  '/protected': typeof ProtectedRoute
  '/Einkauf': typeof EinkaufIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/Einkauf/$maId': typeof EinkaufMaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/not_allowed': typeof Not_allowedRoute
  '/protected': typeof ProtectedRoute
  '/Einkauf/': typeof EinkaufIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/Einkauf/$maId/': typeof EinkaufMaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/not_allowed'
    | '/protected'
    | '/Einkauf/'
    | '/api/auth/$'
    | '/Einkauf/$maId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/not_allowed'
    | '/protected'
    | '/Einkauf'
    | '/api/auth/$'
    | '/Einkauf/$maId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/not_allowed'
    | '/protected'
    | '/Einkauf/'
    | '/api/auth/$'
    | '/Einkauf/$maId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  Not_allowedRoute: typeof Not_allowedRoute
  ProtectedRoute: typeof ProtectedRoute
  EinkaufIndexRoute: typeof EinkaufIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  EinkaufMaIdIndexRoute: typeof EinkaufMaIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/protected': {
      id: '/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not_allowed': {
      id: '/not_allowed'
      path: '/not_allowed'
      fullPath: '/not_allowed'
      preLoaderRoute: typeof Not_allowedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Einkauf/': {
      id: '/Einkauf/'
      path: '/Einkauf'
      fullPath: '/Einkauf/'
      preLoaderRoute: typeof EinkaufIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Einkauf/$maId/': {
      id: '/Einkauf/$maId/'
      path: '/Einkauf/$maId'
      fullPath: '/Einkauf/$maId/'
      preLoaderRoute: typeof EinkaufMaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  Not_allowedRoute: Not_allowedRoute,
  ProtectedRoute: ProtectedRoute,
  EinkaufIndexRoute: EinkaufIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  EinkaufMaIdIndexRoute: EinkaufMaIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
