// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma-viktor-database/schema.prisma",
  migrations: {
    path: "prisma-viktor-database/migrations",
  },
  datasource: {
    url: `mysql://${env("DATABASE_USER")}:${env("DATABASE_PASSWORD")}@${env("DATABASE_HOST")}:3306/${env("DATABASE_NAME")}`,
  },
});
